version: '3.8'

services:
  data_service:
    build:
      context: ./data_service
      dockerfile: Dockerfile
    container_name: data_service
    ports:
      - "8080:8080"
    environment:
      - PORT=8080
      - EXCHANGE_API_KEY=${EXCHANGE_API_KEY}
      # - OTEL_EXPORTER_OTLP_ENDPOINT=otel-collector:4317
    networks:
      - crypto_telemetry_network
    restart: unless-stopped

  # decision_service

  # notifier_service

  # otel_collector

  # grafana 

  # prometheus

  # loki 

  # tempo



networks:
  crypto_telemetry_network:
    driver: bridge
