services:
  data_service:
    build:
      context: ./data_service
      dockerfile: Dockerfile
    container_name: data_service
    ports:
      - "8080:8080"
    env_file:
      - .env
    environment:
      - PORT=8080
      - OTEL_EXPORTER_OTLP_ENDPOINT=otel-collector:4317
    networks:
      - crypto_telemetry_network
    restart: unless-stopped
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:8080/health"]
      interval: 10s
      timeout: 3s
      retries: 3
      start_period: 10s

  decision_service:
    build:
      context: ./decision_service
      dockerfile: Dockerfile
    container_name: decision_service
    ports:
      - "8081:8081"
    env_file:
      - .env
    environment:
      - PORT=8081
      - OTEL_EXPORTER_OTLP_ENDPOINT=otel-collector:4318
    networks:
      - crypto_telemetry_network
    restart: unless-stopped
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:8081/health"]
      interval: 10s
      timeout: 3s
      retries: 3
      start_period: 10s

  notifier_service:
    build:
      context: ./notifier_service
      dockerfile: Dockerfile
    container_name: notirier_service
    ports:
      - "8082:8082"
    env_file:
      - ./notifier_service/notifier.config
    networks:
      - crypto_telemetry_network
    restart: unless-stopped
    # healthcheck:
    #   test: ["CMD", "curl", "-f", "http://localhost:8082/health"]
    #   interval: 10s
    #   timeout: 3s
    #   retries: 3
    #   start_period: 10s


  # Observability Stack
  otel-collector:
    image: otel/opentelemetry-collector-contrib:0.139.0
    container_name: otel-collector
    command: ["--config=/etc/otel-collector-config.yaml"]
    volumes:
      - ./observability/otel-collector/otel-collector-config.yaml:/etc/otel-collector-config.yaml
    ports:
      - "4317:4317"
      - "4318:4318"
      - "8888:8888"
      - "8889:8889"
    networks:
      - crypto_telemetry_network
    restart: unless-stopped
    depends_on:
      - tempo
      # - loki

  prometheus:
    image: prom/prometheus:v2.48.1
    container_name: prometheus
    command:
      - '--config.file=/etc/prometheus/prometheus.yml'
      - '--storage.tsdb.path=/prometheus'
      - '--storage.tsdb.retention.time=2h'
      - '--web.console.libraries=/etc/prometheus/console_libraries'
      - '--web.console.templates=/etc/prometheus/consoles'
      - '--web.enable-lifecycle'
    volumes:
      - ./observability/prometheus/prometheus.yml:/etc/prometheus/prometheus.yml
      - prometheus_data:/prometheus
    ports:
      - "9090:9090"
    networks:
      - crypto_telemetry_network
    restart: unless-stopped

  tempo:
    image: grafana/tempo:2.3.1
    container_name: tempo
    command: ["-config.file=/etc/tempo.yaml"]
    volumes:
      - ./observability/tempo/tempo.yaml:/etc/tempo.yaml
      - tempo_data:/tmp/tempo
    ports:
      - "3200:3200"   # tempo
      - "4317"        # otlp grpc
      - "4318"        # otlp http
    networks:
      - crypto_telemetry_network
    restart: unless-stopped

  # decision_service

  # loki:
  #   image: grafana/loki:2.9.3
  #   container_name: loki
  #   command: -config.file=/etc/loki/loki.yaml
  #   volumes:
  #     - ./observability/loki/loki.yaml:/etc/loki/loki.yaml
  #     - loki_data:/tmp/loki
  #   ports:
  #     - "3100:3100"
  #   networks:
  #     - crypto_telemetry_network
  #   restart: unless-stopped

  grafana:
    image: grafana/grafana:10.2.3
    container_name: grafana
    volumes:
      - ./observability/grafana/provisioning:/etc/grafana/provisioning
      - grafana_data:/var/lib/grafana
    environment:
      - GF_SECURITY_ADMIN_USER=admin
      - GF_SECURITY_ADMIN_PASSWORD=admin
      - GF_USERS_ALLOW_SIGN_UP=false
      - GF_FEATURE_TOGGLES_ENABLE=traceqlEditor
    ports:
      - "3000:3000"
    networks:
      - crypto_telemetry_network
    restart: unless-stopped
    depends_on:
      - prometheus
      - tempo
      # - loki

  # Mock service for testing
  # mock-telemetry-service:
  #   build:
  #     context: ./mock_telemetry_service
  #     dockerfile: Dockerfile
  #   container_name: mock-telemetry-service
  #   environment:
  #     - OTEL_EXPORTER_OTLP_ENDPOINT=http://otel-collector:4318
  #     - OTEL_SERVICE_NAME=mock-telemetry-service
  #   networks:
  #     - crypto_telemetry_network
  #   restart: unless-stopped
  #   depends_on:
  #     - otel-collector


volumes:
  prometheus_data:
  tempo_data:
  # loki_data:
  grafana_data:

networks:
  crypto_telemetry_network:
    driver: bridge
